ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Install Twingate
RUN apt-get update && echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | tee /etc/apt/sources.list.d/twingate.list && \
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
    apt install -yq twingate
COPY ./src/ubuntu/install/twingate_desktop/tgfiles /etc/twingate
COPY ./src/ubuntu/install/twingate_desktop/auth_files /var/lib/twingate
COPY ./src/ubuntu/install/twingate_desktop/custom_startup.sh $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/twingate_desktop/twingate_init.sh $STARTUPDIR/twingate_init.sh
RUN chmod +x $STARTUPDIR/twingate_init.sh && \
    chmod +x $STARTUPDIR/custom_startup.sh && \
    # echo "kasm-user ALL= NOPASSWD: /usr/bin/twingate" >> /etc/sudoers && \
    echo "kasm-user ALL=(ALL) NOPASSWD: /dockerstartup/twingate_init.sh" >> /etc/sudoers
RUN echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/misc/install_tools.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/sublime_text/install_sublime_text.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/remmina/install_remmina.sh \
                  /ubuntu/install/ansible/install_ansible.sh \
                  /ubuntu/install/terraform/install_terraform.sh \
                  /ubuntu/install/dbeaver/install_dbeaver.sh \
                  /ubuntu/install/postman/install_postman.sh \
                  /ubuntu/install/cleanup/cleanup.sh"
#    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
#                  /ubuntu/install/misc/install_tools.sh \
#                  /ubuntu/install/chrome/install_chrome.sh \
#                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}


# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
