FROM europe-west2-docker.pkg.dev/twingate-labs/tg-agentless-images/tg-desktop:dev

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

# Customisation Here
RUN echo "customisation test" > customisation_test.txt && \
sudo apt-get update  && \
sudo apt-get install openjdk-8-jre -y && \
wget https://github.com/karakun/OpenWebStart/releases/download/v1.10.1/OpenWebStart_linux_1_10_1.deb && \
sudo dpkg -i OpenWebStart_linux_1_10_1.deb && \
curl https://tex-int.360t.com/tex.jnlp > /home/kasm-user/Desktop/tex.jnlp && \
sudo rm -rf /var/lib/apt/lists/*

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
