ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

### Install Twingate
RUN apt-get update && echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | tee /etc/apt/sources.list.d/twingate.list && \
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
    apt install -yq twingate
COPY ./src/ubuntu/install/twingate_chrome/tgfiles /etc/twingate
COPY ./src/ubuntu/install/twingate_chrome/auth_files /var/lib/twingate
COPY ./src/ubuntu/install/twingate_chrome/custom_startup.sh $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/twingate_chrome/twingate_init.sh $STARTUPDIR/twingate_init.sh
RUN chmod +x $STARTUPDIR/twingate_init.sh && \
    chmod +x $STARTUPDIR/custom_startup.sh && \
    # echo "kasm-user ALL= NOPASSWD: /usr/bin/twingate" >> /etc/sudoers && \
    echo "kasm-user ALL=(ALL) NOPASSWD: /dockerstartup/twingate_init.sh" >> /etc/sudoers
RUN echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers


# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

## Update the desktop environment to be optimized for a single application
#RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
#RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
#RUN apt-get remove -y xfce4-panel
#
## Security modifications
#COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
#RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/
#COPY ./src/common/chrome-managed-policies/urlblocklist.json /etc/opt/chrome/policies/managed/urlblocklist.json
#
## Setup the custom startup script that will be invoked when the container starts
##ENV LAUNCH_URL  http://kasmweb.com
#
#COPY ./src/ubuntu/install/chrome/custom_startup.sh $STARTUPDIR/custom_startup.sh
#RUN chmod +x $STARTUPDIR/custom_startup.sh
#
## Install Custom Certificate Authority
## COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
## RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/
#
#ENV KASM_RESTRICTED_FILE_CHOOSER=1
#COPY ./src/ubuntu/install/gtk/ $INST_SCRIPTS/gtk/
#RUN bash $INST_SCRIPTS/gtk/install_restricted_file_chooser.sh


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
