FROM europe-west2-docker.pkg.dev/twingate-labs/tg-agentless-images/tg-desktop:dev

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

# Customisation Here
RUN echo "customisation test" > customisation_test.txt

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
