name: deploy-docs
#on:
#  schedule:
#    - cron: "0 0 * * *"

on: [workflow_dispatch]


env:
  PROJECT_ID: twingate-labs
  REGION: europe-west2
  GAR_LOCATION: europe-west2-docker.pkg.dev/twingate-labs/tg-agentless-images/

jobs:
  build_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./dockerfile-kasm-chrome
            image: europe-west2-docker.pkg.dev/twingate-labs/tg-agentless-images/tg-chrome-github-test:dev
          - dockerfile: ./dockerfile-kasm-ubuntu-jammy-desktop
            image: europe-west2-docker.pkg.dev/twingate-labs/tg-agentless-images/tg-desktop-github-test:dev
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          
      - name: Build image
        run: docker build . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image }}
        working-directory: WORKING_DIRECTORY

      - name: Build image
        run: docker image ls

#      - name: Push image
#        run: docker push ${{ env.GAR_LOCATION }}
